steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--output=type=registry",
        "-t",
        "europe-west9-docker.pkg.dev/algorithmic-quartet/training-pipelines/pokemon-trainer:latest",
        "training/",
      ]
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args:
      [
        "-c",
        "docker run -i -e LIGHTNING_API_KEY -e LIGHTNING_USER_ID -e LIGHTNING_ORGANIZATION -e LIGHTNING_TEAMSPACE -e LIGHTNING_STUDIO -e WANDB_API_KEY -e GC_BUCKET_KEY europe-west9-docker.pkg.dev/algorithmic-quartet/training-pipelines/lightning-executor:latest",
      ]
    secretEnv:
      [
        "LIGHTNING_API_KEY",
        "LIGHTNING_USER_ID",
        "LIGHTNING_ORGANIZATION",
        "LIGHTNING_TEAMSPACE",
        "LIGHTNING_STUDIO",
        "WANDB_API_KEY",
        "GC_BUCKET_KEY",
      ]
images:
  - "europe-west9-docker.pkg.dev/algorithmic-quartet/training-pipelines/pokemon-trainer"
  - "europe-west9-docker.pkg.dev/algorithmic-quartet/training-pipelines/lightning-executor"
availableSecrets:
  secretManager:
    - versionName: projects/algorithmic-quartet/secrets/LIGHTNING_API_KEY/versions/latest
      env: "LIGHTNING_API_KEY"
    - versionName: projects/algorithmic-quartet/secrets/LIGHTNING_USER_ID/versions/latest
      env: "LIGHTNING_USER_ID"
    - versionName: projects/algorithmic-quartet/secrets/LIGHTNING_ORGANIZATION/versions/latest
      env: "LIGHTNING_ORGANIZATION"
    - versionName: projects/algorithmic-quartet/secrets/LIGHTNING_TEAMSPACE/versions/latest
      env: "LIGHTNING_TEAMSPACE"
    - versionName: projects/algorithmic-quartet/secrets/LIGHTNING_STUDIO/versions/latest
      env: "LIGHTNING_STUDIO"
    - versionName: projects/algorithmic-quartet/secrets/WANDB_API_KEY/versions/latest
      env: "WANDB_API_KEY"
    - versionName: projects/algorithmic-quartet/secrets/GC_BUCKET_KEY/versions/latest
      env: "GC_BUCKET_KEY"
