steps:
  # - name: "gcr.io/cloud-builders/docker"
  #   args:
  #     [
  #       "build",
  #       "-t",
  #       "europe-west9-docker.pkg.dev/algorithmic-quartet/training-pipelines/pokemon-trainer:latest",
  #       "training/",
  #     ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "run",
        "-e $$LIGHTNING_API_KEY",
        "-e $$LIGHTNING_USER_ID",
        "-e $$LIGHTNING_ORGANIZATION",
        "-e $$LIGHTNING_TEAMSPACE",
        "-e $$LIGHTNING_STUDIO",
        "europe-west9-docker.pkg.dev/algorithmic-quartet/training-pipelines/lightning-executor:latest",
      ]
    # images:
    #   - "europe-west9-docker.pkg.dev/algorithmic-quartet/training-pipelines/lightning-executor:latest"
