steps:
  - name: "gcr.io/cloud-builders/docker"
    id: PullFastAPICache
    entrypoint: "bash"
    args:
      [
        "-c",
        "docker pull europe-west1-docker.pkg.dev/$PROJECT_ID/pokemon-server-images/pokemon-server:latest || exit 0",
      ]
  - name: "gcr.io/cloud-builders/docker"
    id: BuildFastAPI
    dir: "./backend"
    args:
      [
        "build",
        "-t",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/pokemon-server-images/pokemon-server",
        "--cache-from",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/pokemon-server-images/pokemon-server:latest",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    id: PushFastAPI
    args:
      [
        "push",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/pokemon-server-images/pokemon-server",
      ]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "pokemon-server",
        "--image",
        "europe-west1-docker.pkg.dev/$PROJECT_ID/pokemon-server-images/pokemon-server",
        "--region",
        "europe-west1",
      ]
