name: Training
run-name: Train a new model on Lightning.ai
on:
  push:
    tags:
      - "train/*"
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LIGHTNING_USER_ID: ${{ secrets.LIGHTNING_USER_ID }}
      LIGHTNING_API_KEY: ${{ secrets.LIGHTNING_API_KEY }}
      LIGHTNING_ORGANIZATION: ${{ secrets.LIGHTNING_ORGANIZATION }}
      LIGHTNING_STUDIO: ${{ secrets.LIGHTNING_STUDIO }}
      LIGHTNING_TEAMSPACE: ${{ secrets.LIGHTNING_TEAMSPACE }}
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: "Install lightning sdk"
        run: "pip install -r ./ci/requirements.txt"
      - name: "Start Lightning Studio and pull code"
        run: "python ./ci/start_studio.py"
      - name: "Testing pipeline on CPU"
        run: "python ./ci/test_pipeline.py"
      - name: "Stop Lightning Studio"
        if: always()
        run: "python ./ci/shutdown_studio.py"
