name: training
run-name: Build and Test Training Pipeline
on:
  push:
    tags:
      - "train/*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: https://europe-west9-docker.pkg.dev
          username: _json_key_base64
          password: ${{ secrets.ARTIFACT_REGISTRY_ACCOUNT }}

      - name: Build and export
        uses: docker/build-push-action@v5
        with:
          context: training/
          tags: europe-west9-docker.pkg.dev/algorithmic-quartet/training-pipelines/pokemon-trainer:latest

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: https://europe-west9-docker.pkg.dev
          username: _json_key_base64
          password: ${{ secrets.ARTIFACT_REGISTRY_ACCOUNT }}

      - name: Run pipeline in testing mode
        run: |
          docker run europe-west9-docker.pkg.dev/algorithmic-quartet/training-pipelines/pokemon-trainer:latest
