name: training
run-name: Build and Test Training Pipeline
on:
  push:
    tags:
      - "train/*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Google Artifact Registry
        uses: docker/login-action@v3
        with:
          registry: https://europe-west9-docker.pkg.dev
          username: _json_key_base64
          password: ${{ secrets.ARTIFACT_REGISTRY_ACCOUNT }}
      - name: Build and export
        run: |
          docker build --output type=tar,dest=/tmp/pokemon-trainer.tar -t europe-west9-docker.pkg.dev/algorithmic-quartet/training-pipelines/pokemon-trainer training/
          docker push europe-west9-docker.pkg.dev/algorithmic-quartet/training-pipelines/pokemon-trainer:latest
      - name: Upload artifact locally
        uses: actions/upload-artifact@v3
        with:
          name: pokemon-trainer
          path: /tmp/pokemon-trainer.tar

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: pokemon-trainer
          path: /tmp
      - name: Load image
        run: |
          docker load --input /tmp/pokemon-trainer.tar
          docker image ls -a
