name: training
run-name: Build and Test Training Pipeline
on:
  push:
    tags:
      - "train/*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: "Install lightning sdk"
        run: "pip install ./ci/requirements.txt"
      - name: "Start Lightning Studio and pull code"
        run: "python ./ci/start_studio.py"
        env: # the following values are parsed from the repository secrets
        LIGHTNING_USER_ID: ${{ secrets.LIGHTNING_USER_ID }}
        LIGHTNING_API_KEY: ${{ secrets.LIGHTNING_API_KEY }}
